### ISSUE TITLE
Problems getting jeChunks on Firefox 50

### ISSUE THREAD

**Issue by ghost** [CENSUS/shadow#1]
Any ideas how to create the xul pkl files? 

1:052> !py C:\\Users\\nopnopnop\\Desktop\\shadow-master\\pykd_driver symbol -d 96

Traceback (most recent call last):

  File "C:\\Users\\nopnopnop\\Desktop\\shadow-master\\pykd_driver.py", line 189, in <module>
    from_xul = xul, from_dom = dom)

  File "C:\Users\nopnopnop\Desktop\shadow-master\shadow.py", line 1047, in dump_symbol
    pfd = open(xul_symbols_pickle, 'rb')

IOError: [Errno 2] No such file or directory: 'C:\\Users\\nopnopnop\\Desktop\\shadow-master\\pdb\\xul-50.0.pdb.pkl'

**Comment by argp** [comment]
I added xul-50.0.pdb.pkl a couple of days ago. Can you pull and re-try?

**Comment by argp** [comment]
Btw, you can use [symhex.py](https://github.com/CENSUS/shadow/blob/master/auxiliary/symhex.py) to create pkl files from xul.pdb files.

**Comment by ghost** [comment]
It works now. Maybe I was using an older version or something. Great work btw.
