### ISSUE TITLE
shadow does not seem to work on 64 bit builds

### ISSUE THREAD

**Issue by jrmuizel** [CENSUS/shadow#4]
e.g this computation only makes sense on 32 bit:
    new_run.reg0_offset = dbg.read_memory(new_run.bin_addr + \
            (9 * jeheap.DWORD_SIZE), jeheap.DWORD_SIZE, proc)

Is it possible to use the debug information for these offsets instead of hardcoding offsets?

**Comment by argp** [comment]
Yes, the new version of shadow which is about to be released here on github addresses all these issues.

We are currently finishing off some testing, and it will be released ASAP.
