### ISSUE TITLE
How to find Available free memory in jemalloc in malloc_stats_print or other methods. 

### ISSUE THREAD

**Issue by neerajshrimali88** [CENSUS/shadow#6]
How to know, what memory is still available for use in jemalloc. 
I am using malloc_stats_print() function. 
Or any other function mallctl_* available for this ?

**Comment by vats-** [comment]
Check out the [jemalloc wiki](https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Basic-Allocator-Statistics) and [manual page](http://jemalloc.net/jemalloc.3.html).
