### ISSUE TITLE
How to use shadow for linux application purposes ?

### ISSUE THREAD

**Issue by neerajshrimali88** [CENSUS/shadow#7]
How to use shadow for linux application purposes ?

**Comment by Bluekezhou** [comment]
I encountered the same question. 
I compiled  jemalloc-4.2.1.tar.gz in kali 2.0, and I wrote a simple program which called malloc function
And then I tried to run command 'jeparse' after malloc function was executed. But I got such exception
Traceback (most recent call last):
  File "/root/desktop/shadow/gdb_driver.py", line 67, in invoke
    shadow.parse(read_content_preview, config_path, do_debug_log=do_debug_log)
  File "/root/桌面/shadow/shadow.py", line 275, in parse
    parse_tcaches(jeheap)
  File "/root/桌面/shadow/shadow.py", line 940, in parse_tcaches
    data_off = dbg.offsetof("pthread_key_data_t" , "data")
  File "/root/桌面/shadow/gdb_engine.py", line 126, in offsetof
    cache_offsets[k] = to_int(gdb.parse_and_eval(expr))
gdb.error: No symbol "pthread_key_data_t" in current context.
Error occurred in Python command: No symbol "pthread_key_data_t" in current context.

**Comment by vats-** [comment]
Hi and sorry for the late reply.

shadow currently supports Firefox and Android applications only.

Support for Linux processes that use jemalloc will be added on the next
update. (we're working on it)

**Comment by gsingh93** [comment]
Was this implemented? Do you have an update on this?

**Comment by gsingh93** [comment]
pinging @vats- or @argp :)

Currently, the `parse_chunks` function in `shadow.py` fails for standalone jemalloc on linux.
